#' ---
#' title: "MIMIC-III definitions and useful datasets"
#' author: "H. David Shea"
#' date: "`r format(Sys.time(),'%d %b %Y')`"
#' output: github_document
#' ---
#'
#+ r setup, include = FALSE
library(DBI)
library(RSQLite)
library(tidyverse)
#+

#' Connect to the MIMIC3 database - for testing only
#'
# base_dir <- here::here("")
# db_file <- fs::path(base_dir, "database/mimic3.db")
# if(dbCanConnect(RSQLite::SQLite(), db_file)) {
#     mimic3 <- dbConnect(RSQLite::SQLite(), db_file)
# } else {
#     stop(str_c("Database file: ", db_file, " not found.", sep=""))
# }

#' Meta data for MIMIC-III tables - pulled from edX MITx HST.953x course material
#'
mimic3_meta_data <-
    tibble::tribble(
        ~Table.Name,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ~Description, ~Primary.Key,                                          ~Foreign.Key,
        "ADMISSIONS",                                                                                                                                                                                                                                                                                                                                                                                                                              "The ADMISSIONS table gives information regarding a patient’s admission to the hospital. Since each unique hospital visit for a patient is assigned a unique HADM_ID, the ADMISSIONS table can be considered as a definition table for HADM_ID. Information available includes timing information for admission and discharge, demographic information, the source of the admission, and so on.",    "HADM_ID",                                          "SUBJECT_ID",
        "CALLOUT",                                                                                                                                                                                                   "The CALLOUT table provides information about ICU discharge planning. When a patient is deemed ready to leave the ICU, they are “called out”. This process involves: (i) a care provider registering that the patient is ready to leave the ICU and detailing any specialized precautions required, (ii) a coordinator acknowledging the patient requires a bed outside the ward, (iii) a variable period of time in order to coordinate the transfer, and finally (iv) an outcome: either the patient is called out (discharged) or the call out event is canceled. This table provides information for all of the above.",           NA,                                 "SUBJECT_ID, HADM_ID",
        "CAREGIVERS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "This table provides information regarding care givers. For example, it would define if a care giver is a research nurse (RN), medical doctor (MD), and so on.",       "CGID",                                                    NA,
        "CHARTEVENTS", "CHARTEVENTS contains all the charted data available for a patient. During their ICU stay, the primary repository of a patient’s information is their electronic chart. The electronic chart displays patients’ routine vital signs and any additional information relevant to their care: ventilator settings, laboratory values, code status, mental status, and so on. As a result, the bulk of information about a patient’s stay is contained in CHARTEVENTS. Furthermore, even though laboratory values are captured elsewhere (LABEVENTS), they are frequently repeated within CHARTEVENTS. This occurs because it is desirable to display the laboratory values on the patient’s electronic chart, and so the values are copied from the database storing laboratory values to the database storing the CHARTEVENTS.",           NA,       "SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID, CGID",
        "CPTEVENTS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "The CPTEVENTS table contains a list of which current procedural terminology codes were billed for which patients. This can be useful for determining if certain procedures have been performed (e.g. ventilation).",           NA, "SUBJECT_ID, HADM_ID, CPT_CD, CPT_NUMBER, CPT_SUFFIX",
        "D_CPT",                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "This table gives some high level information regarding current procedural terminology (CPT) codes. Unfortunately, detailed information for individual codes is unavailable. Unlike all other definition tables, D_CPT does not have a one to one mapping with the corresponding CPT_CD in CPTEVENTS, rather each row of D_CPT maps to a range of CPT_CD.",           NA,                       "SECTIONRANGE, SUBSECTIONRANGE",
        "D_ICD_DIAGNOSES",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "This table defines International Classification of Diseases Version 9 (ICD-9) codes for diagnoses. These codes are assigned at the end of the patient’s stay and are used by the hospital to bill for care provided.",  "ICD9_CODE",                                                    NA,
        "D_ICD_PROCEDURES",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "This table defines International Classification of Diseases Version 9 (ICD-9) codes for procedures. These codes are assigned at the end of the patient’s stay and are used by the hospital to bill for care provided. They can further be used to identify if certain procedures have been performed (e.g. surgery).",  "ICD9_CODE",                                                    NA,
        "D_ITEMS",                                                                                                                                                                                                                                                                                                                               "The D_ITEMS table defines ITEMID, which represents measurements in the database. Measurements of the same type (e.g. heart rate) will have the same ITEMID (e.g. 211). The ITEMID column is an alternate primary key to this table: it is unique to each row. Note that the D_ITEMS table is sourced from two ICU databases: Metavision and CareVue. Each system had its own set of ITEMID to identify concepts. As a result, there are multiple ITEMID which correspond to the same concept.",     "ITEMID",                                                    NA,
        "D_LABITEMS",                                                                                                                                                                                                                                                                                                                                                                                             "D_LABITEMS contains definitions for all ITEMID associated with lab measurements in the MIMIC database. All data in LABEVENTS link to the D_LABITEMS table. Each unique LABEL in the hospital database was assigned an ITEMID in this table, and the use of this ITEMID facilitates efficient storage and querying of the data. Note that lab items are kept separate while most definitions are contained in the D_ITEMS table.",     "ITEMID",                                                    NA,
        "DATETIMEEVENTS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "DATETIMEEVENTS contains all date measurements about a patient in the ICU. For example, the date of last dialysis would be in the DATETIMEEVENTS table, but the systolic blood pressure would not be in this table.",           NA,       "SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID, CGID",
        "DIAGNOSES_ICD",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "This table contains the ICD9 codes that were attributed to each patient during their stay in the ICU for billing purposes.",           NA,                      "SUBJECT_ID, HADM_ID, ICD9_CODE",
        "DRGCODES",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "This table contains diagnosis related groups (DRG) codes for patients. HCFA-DRG and MS-DRG codes have multiple descriptions as they have changed over time. Sometimes these descriptions are similar, but sometimes they are completely different diagnoses. Users will need to select rows using both the code and the description.",   "DRG_CODE",                                 "SUBJECT_ID, HADM_ID",
        "ICUSTAYS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              "This table defines each ICUSTAY_ID in the database, i.e. defines a single ICU stay. It is derived from the TRANSFERS table. Specifically, it groups the TRANSFERS table based on ICUSTAY_ID, and excludes rows where no ICUSTAY_ID is present.", "ICUSTAY_ID",                                 "SUBJECT_ID, HADM_ID",
        "INPUTEVENTS_CV",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           "This table has input data for patients under the careview system.",           NA,       "SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID, CGID",
        "INPUTEVENTS_MV",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         "This table has input data for patients under the metavision system.",           NA,       "SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID, CGID",
        "LABEVENTS",                                                                                                                                                                                                                                                                                                                           "The LABEVENTS data contains information regarding laboratory based measurements. The process for acquiring a lab measurement is as follows: first, a member of the clinical staff acquires a fluid from a site in the patient’s body (e.g. blood from an arterial line, urine from a catheter, etc). Next, the fluid is bar coded to associate it with the patient and timestamped to record the time of the fluid acquisition. The lab analyses the data and returns a result within 4-12 hours.",           NA,                         "SUBJECT_ID, HADM_ID, ITEMID",
        "MICROBIOLOGYEVENTS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "This table contains microbiology information, including tests performed and sensitivities.",           NA,                         "SUBJECT_ID, HADM_ID, ITEMID",
        "NOTEEVENTS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 "This table contains all notes for patients.",           NA,                           "SUBJECT_ID, HADM_ID, CGID",
        "OUTPUTEVENTS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "This table contains output data for patients.",           NA,       "SUBJECT_ID, HADM_ID, CGID, ICUSTAY_ID, ITEMID",
        "PATIENTS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "This table contains all charted data for all patients.", "SUBJECT_ID",                                                    NA,
        "PRESCRIPTIONS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "This table contains medication related order entries, i.e. prescriptions.",           NA,                     "SUBJECT_ID, HADM_ID, ICUSTAY_ID",
        "PROCEDUREEVENTS_MV",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "This table contains information on procedures performed on patients under the metavision system.",           NA,             "SUBJECT_ID, HADM_ID, ICUSTAY_ID, ITEMID",
        "PROCEDURES_ICD",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       "This table contains the ICD9 codes for the procedures performed on the patients for billing purposes.",           NA,                      "SUBJECT_ID, HADM_ID, ICD9_CODE",
        "SERVICES",                                                                                                                                                                                                                                          "The services table describes the service that a patient was admitted under. While a patient can be physicially located at a given ICU type (say MICU), they are not necessarily being cared for by the team which staffs the MICU. This can happen due to a number of reasons, including bed shortage. The SERVICES table should be used if interested in identifying the type of service a patient is receiving in the hospital. For example, if interested in identifying surgical patients, the recommended method is searching for patients admitted under a surgical service.",           NA,                                 "SUBJECT_ID, HADM_ID",
        "TRANFERS",                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   "This table keeps track of the patient's physical location throughout their hospital stay.",           NA,                     "SUBJECT_ID, HADM_ID, ICUSTAY_ID"
    )

mimic3_service_descritions <-
tibble::tribble(
    ~SERVICE,                                                                                ~DESCRIPTION,
      "CMED",                             "Cardiac Medical - for non-surgical cardiac related admissions",
     "CSURG",                                         "Cardiac Surgery - for surgical cardiac admissions",
      "DENT",                                                "Dental - for dental/jaw related admissions",
       "ENT",                        "Ear, nose, and throat - conditions primarily affecting these areas",
        "GU",                                        "Genitourinary - reproductive organs/urinary system",
       "GYN",                                   "Gynecological - female reproductive systems and breasts",
       "MED",                                           "Medical - general service for internal medicine",
        "NB",                                                    "Newborn - infants born at the hospital",
       "NBB",                                               "Newborn baby - infants born at the hospital",
      "NMED",                                  "Neurologic Medical - non-surgical, relating to the brain",
     "NSURG",                                     "Neurologic Surgical - surgical, relating to the brain",
       "OBS",                  "Obstetrics - conerned with childbirth and the care of women giving birth",
     "ORTHO",                            "Orthopaedic - surgical, relating to the musculoskeletal system",
      "OMED",                   "Orthopaedic medicine - non-surgical, relating to musculoskeletal system",
     "PSURG", "Plastic - restortation/reconstruction of the human body (including cosmetic or aesthetic)",
     "PSYCH",     "Psychiatric - mental disorders relating to mood, behaviour, cognition, or perceptions",
      "SURG",                              "Surgical - general surgical service not classified elsewhere",
     "TRAUM",                 "Trauma - injury or damage caused by physical harm from an external source",
     "TSURG",       "Thoracic Surgical - surgery on the thorax, located between the neck and the abdomen",
     "VSURG",                            "Vascular Surgical - surgery relating to the circulatory system"
    )
mimic3_service_descritions <- mimic3_service_descritions %>%
    mutate(
        SHORT_DESCRIPTION = str_split(DESCRIPTION, " - ", simplify = TRUE)[,1]
    )

# used to replicate the mimic-iii demo set for exercises using those data
mimic_demo_cohort <- c(
    10006, 10011, 10013, 10017, 10019, 10026, 10027, 10029, 10032, 10033,
    10035, 10036, 10038, 10040, 10042, 10043, 10044, 10045, 10046, 10056,
    10059, 10061, 10064, 10065, 10067, 10069, 10074, 10076, 10083, 10088,
    10089, 10090, 10093, 10094, 10098, 10101, 10102, 10104, 10106, 10111,
    10112, 10114, 10117, 10119, 10120, 10124, 10126, 10127, 10130, 10132,
    40124, 40177, 40204, 40277, 40286, 40304, 40310, 40456, 40503, 40595,
    40601, 40612, 40655, 40687, 41795, 41914, 41976, 41983, 42033, 42066,
    42075, 42135, 42199, 42231, 42275, 42281, 42292, 42302, 42321, 42346,
    42367, 42412, 42430, 42458, 43735, 43746, 43748, 43779, 43798, 43827,
    43870, 43879, 43881, 43909, 43927, 44083, 44154, 44212, 44222, 44228)


#' Disconnect from the MIMIC3 database - for testing code only
#'
# dbDisconnect(mimic3)
